#if !defined(INPUT_HPP)
#define INPUT_HPP
/**
 * Description:  Input Codes
 * Author:       Alicia Amarilla (smushyaa@gmail.com)
 * File Created: May 01, 2023
*/
#include "defines.h"

/// Key Codes
enum KeyCode : u16 {
    KC_UNKNOWN = U16::MAX,
    KC_SPACE = 0,
    KC_A,
    KC_B,
    KC_C,
    KC_D,
    KC_E,
    KC_F,
    KC_G,
    KC_H,
    KC_I,
    KC_J,
    KC_K,
    KC_L,
    KC_M,
    KC_N,
    KC_O,
    KC_P,
    KC_Q,
    KC_R,
    KC_S,
    KC_T,
    KC_U,
    KC_V,
    KC_W,
    KC_X,
    KC_Y,
    KC_Z,
    KC_ESCAPE,
    KC_F1,
    KC_F2,
    KC_F3,
    KC_F4,
    KC_F5,
    KC_F6,
    KC_F7,
    KC_F8,
    KC_F9,
    KC_F10,
    KC_F11,
    KC_F12,
    KC_F13,
    KC_F14,
    KC_F15,
    KC_F16,
    KC_F17,
    KC_F18,
    KC_F19,
    KC_F20,
    KC_F21,
    KC_F22,
    KC_F23,
    KC_F24,
    KC_PRINT_SCREEN,
    KC_SCROLL_LOCK,
    KC_PAUSE,
    KC_BACKTICK,
    KC_0,
    KC_1,
    KC_2,
    KC_3,
    KC_4,
    KC_5,
    KC_6,
    KC_7,
    KC_8,
    KC_9,
    KC_MINUS,
    KC_EQUALS,
    KC_BACKSPACE,
    KC_INSERT,
    KC_HOME,
    KC_PAGE_UP,
    KC_TAB,
    KC_BRACKET_LEFT,
    KC_BRACKET_RIGHT,
    KC_SLASH_BACKWARD,
    KC_DELETE,
    KC_END,
    KC_PAGE_DOWN,
    KC_CAPSLOCK,
    KC_SEMICOLON,
    KC_QUOTE,
    KC_ENTER,
    KC_SHIFT_LEFT,
    KC_COMMA,
    KC_PERIOD,
    KC_SLASH_FORWARD,
    KC_SHIFT_RIGHT,
    KC_CONTROL_LEFT,
    KC_SUPER_LEFT,
    KC_ALT_LEFT,
    KC_ALT_RIGHT,
    KC_SUPER_RIGHT,
    KC_CONTROL_RIGHT,
    KC_ARROW_LEFT,
    KC_ARROW_RIGHT,
    KC_ARROW_UP,
    KC_ARROW_DOWN,
    KC_NUM_LOCK,
    KC_PAD_0,
    KC_PAD_1,
    KC_PAD_2,
    KC_PAD_3,
    KC_PAD_4,
    KC_PAD_5,
    KC_PAD_6,
    KC_PAD_7,
    KC_PAD_8,
    KC_PAD_9,

    KC_COUNT
};
inline const char* to_string( KeyCode keycode ) {
    SM_LOCAL const char* strings[KC_COUNT] = {
        "Space",
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        "Escape",
        "F1",
        "F2",
        "F3",
        "F4",
        "F5",
        "F6",
        "F7",
        "F8",
        "F9",
        "F10",
        "F11",
        "F12",
        "F13",
        "F14",
        "F15",
        "F16",
        "F17",
        "F18",
        "F19",
        "F20",
        "F21",
        "F22",
        "F23",
        "F24",
        "Print Screen",
        "Scroll Lock",
        "Pause",
        "`~",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "-_",
        "=+",
        "Backspace",
        "Insert",
        "Home",
        "PageUp",
        "Tab",
        "[{",
        "]}",
        "\\|",
        "Delete",
        "End",
        "Page Down",
        "Capslock",
        ";:",
        "\'\"",
        "Enter",
        "Left Shift",
        ",<",
        ".>",
        "/?",
        "Right Shift",
        "Left Control",
        "Left Super",
        "Left Alt",
        "Right Alt",
        "Right Super",
        "Right Control",
        "Left Arrow",
        "Right Arrow",
        "Up Arrow",
        "Down Arrow",
        "Numlock",
        "Keypad 0",
        "Keypad 1",
        "Keypad 2",
        "Keypad 3",
        "Keypad 4",
        "Keypad 5",
        "Keypad 6",
        "Keypad 7",
        "Keypad 8",
        "Keypad 9",
    };
    if( keycode >= KC_COUNT ) {
        return "Unknown";
    }
    return strings[keycode];
}

/// Mouse Button Codes
enum MouseCode : u16 {
    MC_UNKNOWN = U16::MAX,
    MC_BUTTON_LEFT = 0,
    MC_BUTTON_MIDDLE,
    MC_BUTTON_RIGHT,
    MC_BUTTON_EXTRA_1,
    MC_BUTTON_EXTRA_2,

    MC_COUNT
};
inline const char* to_string( MouseCode mousecode ) {
    SM_LOCAL const char* strings[MC_COUNT] = {
        "Mouse Button Left",
        "Mouse Button Middle",
        "Mouse Button Right",
        "Mouse Button Extra 1",
        "Mouse Button Extra 2",
    };
    if( mousecode >= MC_COUNT ) {
        return "Unknown";
    }
    return strings[mousecode];
}

#endif