#if !defined(LD_PACKAGE_ERROR_H)
#define LD_PACKAGE_ERROR_H
/**
 * Description:  Error codes.
 * Author:       Alicia Amarilla (smushyaa@gmail.com)
 * File Created: January 09, 2024
*/

typedef enum PackageError : int {
    PACKAGE_SUCCESS,
    PACKAGE_ERROR_NO_ARGUMENTS = 128,
    PACKAGE_ERROR_UNRECOGNIZED_ARGUMENT,
    PACKAGE_ERROR_INVALID_ARGUMENTS,
    PACKAGE_ERROR_MISSING_MANIFEST_PATH,
    PACKAGE_ERROR_INITIALIZE_LOGGING,
    PACKAGE_ERROR_OUT_OF_MEMORY,
    PACKAGE_ERROR_CREATE_JOB_SYSTEM,
    PACKAGE_ERROR_OPEN_FILE,
    PACKAGE_ERROR_READ_FILE,
    PACKAGE_ERROR_WRITE_FILE,
    PACKAGE_ERROR_PARSE_MANIFEST,
    PACKAGE_ERROR_PROCESS_RESOURCE,
    PACKAGE_ERROR_CREATE_TEMP_DIRECTORY,

    PACKAGE_ERROR_UNIMPLEMENTED
} PackageError;

#endif /* header guard */
