/**
 * Description:  Utility Package Header Generator Implementation.
 * Author:       Alicia Amarilla (smushyaa@gmail.com)
 * File Created: January 09, 2024
*/
#include "shared/defines.h"
#include "core/string.h"

#include "package/manifest.h"
#include "package/error.h"
#include "package/header.h"
#include "package/logging.h"

#include "core/fs.h"
#include "core/time.h"
#include "core/rand.h"
#include "core/string.h"

void job_header_generate( usize thread_index, void* opaque_params ) {
    HeaderGeneratorParams* params = opaque_params;
    Manifest* manifest = params->manifest;

    FileOpenFlags header_open_flags =
        FILE_OPEN_FLAG_WRITE | FILE_OPEN_FLAG_SHARE_ACCESS_READ;
    /* check if header exists */ {
        FileHandle* header = fs_file_open( params->output_path, FILE_OPEN_FLAG_READ );
        if( !header ) {
            header_open_flags |= FILE_OPEN_FLAG_CREATE;
        } else {
            header_open_flags |= FILE_OPEN_FLAG_TRUNCATE;
            fs_file_close( header );
        }
    }
    FileHandle* header_file = fs_file_open( params->output_path, header_open_flags );
    if( !header_file ) {
        log_error(
            "failed to open header output file! path: '{p}'", params->output_path );
        params->error = PACKAGE_ERROR_OPEN_FILE;
        return;
    }

    #define write( format, ... ) do {\
        if( !fs_file_write_fmt( header_file, format, ##__VA_ARGS__ ) ) {\
            log_error( "failed to write to header file '{p}'!", params->output_path );\
            goto job_header_generate_end;\
        }\
    } while(0)
    #define writeln( format, ... )\
        write( format "\n", ##__VA_ARGS__ )

    TimeRecord time = time_record();

    StringSlice header_name = {};
    if( path_slice_get_file_stem( params->output_path, &header_name ) ) {
        writeln( "#if !defined( GENERATED_{s,u}_H )", header_name );
        writeln( "#define GENERATED_{s,u}_H", header_name );
    } else {
        u32 random_id = rand_xor_u32();
        writeln( "#if !defined( GENERATED_RESOURCE_IDS_{u32}_H )", random_id );
        writeln( "#define GENERATED_RESOURCE_IDS_{u32}_H", random_id );
    }
    writeln( "/**" );
    writeln( " * Description:    Package resource id header." );
    writeln( " * Generated by:   Utility Package" );
    writeln( " * File Generated: {cc} {u,02}, {u,04}",
        time_month_to_cstr( time.month ), time.day, time.year );
    writeln( "*/" );
    writeln( "#include \"shared/defines.h\"\n" );

    for( u32 i = 0; i < params->manifest->items.count; ++i ) {
        ManifestItem* item = manifest->items.buffer + i;
        usize padding =
            manifest->longest_identifier_length
            - item->identifier.len;

        StringSlice type_slice = {};
        type_slice.str = package_resource_type_to_cstr(
            item->type, &type_slice.len );

        padding += manifest->longest_type_name_length - type_slice.len;
        writeln(
            "#define RESOURCE_{s,u}_{s}{c,r_}({u32}u)",
            type_slice, item->identifier, padding, ' ', i + 1 );
    }

    writeln( "\n#endif /* header guard */" );
    log_print( "successfully created header at path '{s}'", params->output_path );

job_header_generate_end:
    fs_file_close( header_file );

    #undef write
    #undef writeln
}

